package atm.core.service;

import atm.core.AtmException;
import atm.core.Database;
import atm.core.Ids;
import atm.core.Log;
import atm.core.Money;
import atm.core.Passwords;
import atm.core.dao.AccountDao;
import atm.core.dao.CardDao;
import atm.core.dao.CustomerDao;
import atm.core.dao.LimitDao;
import atm.core.model.Account;
import atm.core.model.AccountType;
import atm.core.model.Customer;
import atm.core.model.Limits;
import atm.core.model.TransactionType;
import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Opening a new account: creates the customer, the account, the card with a hashed PIN and
 * the default limits in <b>one</b> transaction, so a signup can never leave half a customer
 * behind. Card number and PIN are generated by the bank, which is what the old flow forgot
 * to do.
 */
public class OnboardingService {

    private final Database db = Database.get();
    private final CustomerDao customers = new CustomerDao();
    private final AccountDao accounts = new AccountDao();
    private final CardDao cards = new CardDao();
    private final LimitDao limits = new LimitDao();
    private final AuditService audit = new AuditService();

    /** Details collected by the three signup screens. */
    public record Application(
        String name,
        String fname,
        String dob,
        String gender,
        String email,
        String marital,
        String address,
        String city,
        String religion,
        String category,
        String income,
        String education,
        String occupation,
        String pan,
        String aadhar,
        String phone,
        String services,
        AccountType accountType,
        BigDecimal openingDeposit) {

        public void validate() {
            if (name == null || name.isBlank()) {
                throw new AtmException(AtmException.Reason.VALIDATION, "Name is required");
            }
            if (phone == null || !phone.replaceAll("\\s", "").matches("\\+?\\d{9,15}")) {
                throw new AtmException(AtmException.Reason.VALIDATION,
                    "A valid phone number is required");
            }
            if (email != null && !email.isBlank()
                    && !email.matches("^[^@\\s]+@[^@\\s]+\\.[A-Za-z]{2,}$")) {
                throw new AtmException(AtmException.Reason.VALIDATION,
                    "Enter a valid email address");
            }
            if (aadhar == null || !aadhar.replaceAll("\\s", "").matches("\\d{6,20}")) {
                throw new AtmException(AtmException.Reason.VALIDATION,
                    "A valid identity number is required");
            }
        }
    }

    /** What the customer must be told: their new card number, PIN and account number. */
    public record NewAccount(String cardNo, String pin, String accountNo, String accountType,
            BigDecimal openingBalance) {
    }

    public NewAccount openAccount(Application app) {
        app.validate();
        BigDecimal opening = Money.scale(app.openingDeposit() == null
            ? BigDecimal.ZERO : app.openingDeposit());
        if (opening.compareTo(BigDecimal.ZERO) < 0) {
            throw new AtmException(AtmException.Reason.VALIDATION, "Opening deposit cannot be negative");
        }

        String cardNo = uniqueCardNo();
        String accountNo = Ids.accountNo();
        String pin = String.valueOf(Passwords.numericCode() % 9000 + 1000);
        String salt = Passwords.newSalt();

        db.tx(c -> {
            customers.insert(c, cardNo, app.name().trim(), app.fname(), app.dob(), app.gender(),
                app.email(), app.marital(), app.address(), app.city(), app.religion(),
                app.category(), app.income(), app.education(), app.occupation(), app.pan(),
                app.aadhar(), app.phone(), app.services(),
                app.accountType() == null ? AccountType.SAVING.code() : app.accountType().code());
            accounts.insert(c, accountNo, cardNo,
                app.accountType() == null ? AccountType.SAVING : app.accountType(), opening);
            cards.insert(c, cardNo, accountNo, Passwords.hash(pin, salt), salt,
                LocalDate.now().plusYears(3));
            limits.upsert(c, accountNo, limits.find(c, accountNo));
            if (opening.compareTo(BigDecimal.ZERO) > 0) {
                new atm.core.dao.TxnDao().insert(c, accountNo, TransactionType.DEPOSIT, opening,
                    opening, "Opening deposit at account creation", Ids.reference(), null, "BRANCH");
            }
            return null;
        });

        audit.log(AuditService.SIGNUP, cardNo,
            "Account " + accountNo + " opened (" + (app.accountType() == null
                ? AccountType.SAVING.code() : app.accountType().code())
                + "), opening deposit " + Money.usd(opening));
        Log.info("New account " + accountNo + " for card " + Ids.maskCard(cardNo));

        return new NewAccount(cardNo, pin, accountNo,
            app.accountType() == null ? AccountType.SAVING.code() : app.accountType().code(), opening);
    }

    /** Registers a customer, creates the account and issues a card, in one go. */
    public NewAccount openAccount(String name, String fname, String phone, String email,
            AccountType type, BigDecimal openingDeposit) {
        return openAccount(new Application(name, fname, "", "", email, "", "", "", "", "", "",
            "", "", "", "", phone, "", type, openingDeposit));
    }

    public boolean cardExists(String cardNo) {
        return db.read(c -> customers.findByCardNo(c, cardNo)) != null;
    }

    public Account accountOf(String cardNo) {
        return db.read(c -> accounts.findByCardNo(c, cardNo));
    }

    public Customer customerOf(String cardNo) {
        return db.read(c -> customers.findByCardNo(c, cardNo));
    }

    public Limits limitsOf(String accountNo) {
        return db.read(c -> limits.find(c, accountNo));
    }

    private String uniqueCardNo() {
        for (int attempt = 0; attempt < 10; attempt++) {
            String candidate = Ids.cardNo();
            if (!cardExists(candidate)) {
                return candidate;
            }
        }
        throw new AtmException(AtmException.Reason.UNAVAILABLE,
            "Could not allocate a card number, please try again");
    }
}
